- id: check-submodules-updated
  name: check-submodules-updated
  entry: scripts/check-submodules-updated
  language: script
  always_run: true
  pass_filenames: false
  description: Check submodules updated
- id: check-submodules-updated-debug
  name: check-submodules-updated-debug
  entry: scripts/check-submodules-updated-debug
  language: script
  always_run: true
  pass_filenames: false
  description: Check submodules updated (debug)
- id: check-version-bumped
  name: check-version-bumped
  entry: scripts/check-version-bumped
  language: script
  always_run: true
  pass_filenames: false
  description: Check version bumped
