#!/usr/bin/env sh

echo_date() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }
get_head() { get_sha HEAD; }
get_sha() { git rev-parse --short "$1"; }
get_version() { git_checkout "$1" && bump-my-version show current_version; }
git_checkout() { git checkout "$1" >/dev/null 2>&1; }
has_one_commit() { git rev-parse --verify HEAD >/dev/null 2>&1; }
have_command() { command -v "$1" >/dev/null 2>&1; }
have_bump_my_version() { have_command 'bump-my-version'; }
is_repo_clean() { [ -z "$(git status --porcelain)" ]; }
is_valid_sha() { git rev-parse --verify "$1^{commit}" >/dev/null 2>&1; }

main() {
	if [ $# -ne 0 ]; then
		echo_date "'check-submodules-updated' accepts 0 arguments; got $#" >&2
		return 1
	fi
	curr_sha=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || get_head)
	local_sha=$(get_head)
	if ! is_valid_sha "${local_sha}"; then
		echo_date "Invalid local SHA; got '${local_sha}'" >&2 && return 1
	fi
	git fetch origin master:refs/remotes/origin/master
	remote_sha=$(get_sha origin/master)
	if ! is_valid_sha "${remote_sha}"; then
		echo_date "Invalid remote SHA; got '${remote_sha}'" >&2 && return 1
	fi
	if ! have_bump_my_version && have_command pip; then
		pip install bump-my-version
	fi
	local_version=$(get_version "${local_sha}")
	remote_version=$(get_version "${remote_sha}")
	git_checkout "${curr_sha}"
	if [ "${local_version}" = "${remote_version}" ]; then
		echo_date "Both local '${local_sha}' and remote '${remote_sha}' have the same version '${local_version}'" >&2 && return 1
	fi
	return 0
}

main "$@"
