#!/usr/bin/env sh

echo_date() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

get_head() { get_sha HEAD; }
get_sha() { git rev-parse --short "$1"; }
get_version() { git_checkout "$1" && bump-my-version show current_version; }
git_checkout() { git checkout "$1" >/dev/null 2>&1; }
has_one_commit() { git rev-parse --verify HEAD >/dev/null 2>&1; }
have_bump_my_version() { command -v bump-my-version >/dev/null 2>&1; }
is_repo_clean() { [ -z "$(git status --porcelain)" ]; }
is_valid_sha() { git rev-parse --verify "$1^{commit}" >/dev/null 2>&1; }

main() {
	if ! has_one_commit; then
		echo_date "There must be at least 1 commit; got none" >&2 && return 1
	elif ! have_bump_my_version; then
		echo_date "'bump-my-version' must be available" >&2 && return 1
	elif ! is_repo_clean; then
		echo_date "Repo must be clean" >&2 && return 1
	elif [ $# -ne 0 ]; then
		echo_date "'check-version-bumped' accepts 0 arguments; got $#" >&2
		return 1
	fi
	curr_sha=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || get_head)
	local_sha=$(get_head)
	if ! is_valid_sha "${local_sha}"; then
		echo_date "Invalid local SHA; got '${local_sha}'" >&2 && return 1
	fi
	remote_sha=$(get_sha origin/master)
	if ! is_valid_sha "${remote_sha}"; then
		echo_date "Invalid remote SHA; got '${remote_sha}'" >&2 && return 1
	fi
	local_version=$(get_version "${local_sha}")
	remote_version=$(get_version "${remote_sha}")
	git_checkout "${curr_sha}"
	if [ "${local_version}" = "${remote_version}" ]; then
		echo_date "Both local '${local_sha}' and remote '${remote_sha}' have the same version '${local_version}'" >&2 && return 1
	else
		return 0
	fi
}

main "$@"
