name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        cache: "pip"
      - run: pip install bump-my-version
      - run: curl -fsSL https://raw.githubusercontent.com/dycw/remote-scripts/refs/heads/master/scripts/check-version-bumped | sh -s

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ludeeus/action-shellcheck@master
